### ISSUE TITLE
Write unit tests for gslab_make

### ISSUE THREAD

**Issue by jcconway** [gentzkow/gslab_make#9]
In accordance with larger project outline on the [wiki](https://github.com/gentzkow/gslab_make/wiki/Project-Outline).

**Comment by gentzkow** [comment]
@jcconway I notice this issue is still open. Can we post a final comment clarifying what has been done / remains to be done and then close?

**Comment by jcconway** [comment]
@gentzkow, thanks for highlighting this hanging issue! I'll confirm with @z-y-huang regarding the conclusion of this issue, and will then summarize and wrap up the issue accordingly. This will also include taking care of the [issue9-write-unit-tests branch](https://github.com/gentzkow/gslab_make/tree/55820a2d0fa61eed59dbeb3d70946965aa01daa1).

**Comment by jcconway** [comment]
@z-y-huang, can you help clarify a few questions I have regarding the conclusion of this issue? My recollection of this issue is that I wrote preliminary unit tests for gslab_make prior to your refactoring of the code in #8. @danielagonzalez was then assigned to expand and update the unit tests accordingly to reflect this refactoring. 

It appears that this later work may have ultimately occurred in #11, and may or may not have been merged in the master as part of your PR #12. Can you confirm whether:
1. This unit testing work continued (and was ultimately completed) in #11 or elsewhere?
2. These updated unit tests were ever merged into the master in PR #12 or elsewhere?
3. The [issue9-write-unit-tests branch](https://github.com/gentzkow/gslab_make/tree/55820a2d0fa61eed59dbeb3d70946965aa01daa1) can be safely deleted?

Thanks in advance for the clarifications!

**Comment by z-y-huang** [comment]
@jcconway:

I believe the unit test work started in #9 and continued in #11, though the branch was kept as `issue9-write-unit-tests`. From the commit history in the `master` branch, it hasn't been merged in yet.

**Comment by jcconway** [comment]
@z-y-huang, thanks! The transition in work from #9 to #11 is also what I had in mind. My recollection is that my unit tests were preliminary and there was room for improvement, and I'm unsure of how much further development occurred in #11. I see that you closed and summarized #11 in the comment [here](https://github.com/gentzkow/gslab_make/issues/11#issuecomment-504585257). Can you clarify whether the unit tests are complete and can now be merged into the master, or is your view that they may require another round of review and edits before this merge?

**Comment by z-y-huang** [comment]
@jcconway:

Daniela had updated the unit tests so that they ran with the refactored version of `gslab_make`. She did not create any new unit tests (so we don't have any coverage for any of the new features we implemented).

I believe the branch should be ready to merge, though you might want to review the code too.

**Comment by jcconway** [comment]
@z-y-huang, it looks like many of these issue9 tests are already included in master. Are you saying that just Daniela's later changes haven't been included, or have I misunderstood?

I also took a brief look at and tried running the unit tests in the [issue9](https://github.com/gentzkow/gslab_make/tree/55820a2d0fa61eed59dbeb3d70946965aa01daa1) branch. My impression was that these seemed to be in ok but not great shape overall, and there's certainly some room for improvement in both the existing tests and in testing the newer features implemented. I also had some of these tests fail. Some failed as expected because I did not have the underlying program (e.g. Mathematica) or because there was some shortcoming in the test (e.g. the test for `remove_path()` looks for the string "Deleted: " which has since been changed to "Removed: ", but this test really should be a check on the actual purpose of the function and not the string output). Other tests, such as some of the `test_path_with_space` tests, seem to have failed for other reasons. I also had some difficulty running these tests via `coverage`, likely due to some local computer issues.

Would you mind also seeing how these issue9 tests run on your machine before we consider merging into the master? I think we'll eventually want to improve on and extend the existing unit tests, but haven't yet decided whether that would be most appropriate to do as part of this open issue vs. as a separate future issue.

**Comment by z-y-huang** [comment]
@jcconway:

It looks like those got inadvertently merged in via `git merge` when I was incorporating some bugfixes from branch `issue9-write-unit-tests`. That branch hasn't actually been officially merged to master though.

I can try running the rests on my machine!

**Comment by jcconway** [comment]
@z-y-huang, understood. Thanks for the clarification and thanks in advance for also running the unit tests on your machine!

**Comment by jcconway** [comment]
@z-y-huang, have you had a chance to run these unit tests on your machine? No rush on this, just wanted to prevent this from becoming a hanging issue again.

**Comment by z-y-huang** [comment]
@jcconway:

Not yet!

**Comment by jcconway** [comment]
@z-y-huang: I'm again flagging this (running and incorporating the existing unit tests) for you as a potential hanging issue, and adding you as a joint assignee. Let me know if there's anything on my end needed to wrap up this issue. Thanks!

**Comment by z-y-huang** [comment]
@jcconway:

I put the results of my run [here](https://github.com/gentzkow/gslab_make/tree/issue9-run-tests). I don't have a Mathematica license, so those are the only tests that weren't run.

Somewhat related note: we should consider eventually switching to [TravisCI](https://travis-ci.org).

**Comment by jcconway** [comment]
Thanks @z-y-huang! I pushed fixes to minor issues in the unit tests themselves which resolve most of [these](https://github.com/gentzkow/gslab_make/issues/9#issuecomment-540064954) isolated failed tests. The remaining errors are as follows:
- `test_run_mathematica`: Many failing tests as expected, as we don't have Mathematica.
- `test_run_matlab`: Many instances in which calls to Matlab exited with errors, not sure why this is occurring.
- `test_run_r.test_path_with_space`: Our call to R exited with errors when including a space in the input code filename.

@z-y-huang can you please look into the remaining failing program calls on the latter two points above? Once these errors are fixed I believe we can wrap up this issue, although further additions and edits to the unit tests would be appropriate in a future issue. This might include a switch to TravisCI as [suggested](https://github.com/gentzkow/gslab_make/issues/9#issuecomment-540064954).

**Comment by z-y-huang** [comment]
Summary:

Initial attempts at porting over and revamping unit tests. Continuing unit test refactoring in new issue.
